In [1]:
import Pkg; Pkg.add("Yao"); Pkg.add("YaoPlots"); Pkg.add("LinearAlgebra"); Pkg.add("Kronecker")

    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
   Installed libva_jll ───────────── v2.23.0+0
   Installed Xorg_libpciaccess_jll ─ v0.19.0+0
   Installed libdrm_jll ──────────── v2.4.125+1
  Installing 3 artifacts
   Installed artifact Xorg_libpciaccess        26.2 KiB
   Installed artifact libva                    235.7 KiB
   Installed artifact libdrm                   368.0 KiB
     Project No packages added to or removed from `~/.julia/environments/v1.12/Project.toml`
    Updating `~/.julia/environments/v1.12/Manifest.toml`
  [a65dc6b1] + Xorg_libpciaccess_jll v0.19.0+0
  [8e53e030] + libdrm_jll v2.4.125+1
  [9a156e7d] + libva_jll v2.23.0+0
Precompiling packages...
    685.4 ms  ✓ IteratorInterfaceExtensions
    758.8 ms  ✓ SimpleUnPack
    719.8 ms  ✓ ConcreteStructs
    729.7 ms  ✓ StatsAPI
    721.1 ms  ✓ InverseFunctions
    768.0 ms  ✓ LaTeXStrings
    812.3 ms  ✓ Contour
    916.3 ms  ✓ Measures
    955.2 ms  ✓ Glob
   1033.8 ms  

   1040.2 ms  ✓ InverseFunctions → InverseFunctionsTestExt
   1909.1 ms  ✓ IntelOpenMP_jll
   2181.3 ms  ✓ PkgVersion
   2086.7 ms  ✓ oneTBB_jll
    898.9 ms  ✓ Primes
   2690.0 ms  ✓ RecipesBase
   1009.0 ms  ✓ Statistics → SparseArraysExt
    670.6 ms  ✓ IntervalSets → IntervalSetsStatisticsExt
    562.4 ms  ✓ FunctionWrappersWrappers
    791.1 ms  ✓ AliasTables
   1972.9 ms  ✓ SignedDistanceFields
   1687.5 ms  ✓ NamedDims
    770.5 ms  ✓ WidgetsBase
   2928.9 ms  ✓ RuntimeGeneratedFunctions
    886.8 ms  ✓ StridedViews
    729.4 ms  ✓ Showoff
   3554.0 ms  ✓ DifferentiationInterface
    702.0 ms  ✓ Adapt
   2277.9 ms  ✓ Missings
   1419.6 ms  ✓ Random123
    599.9 ms  ✓ Ratios
   3321.3 ms  ✓ ComputePipeline
   2463.6 ms  ✓ Jieko
  12579.2 ms  ✓ Krylov
   1032.5 ms  ✓ CodecZlib
   2928.1 ms  ✓ AbstractFFTs → AbstractFFTsTestExt
   5237.5 ms  ✓ TimerOutputs
   4784.5 ms  ✓ FixedPointNumbers
    712.4 ms  ✓ DiffResults
    831.8 ms  ✓ LogExpFunctions
    663.2 ms  ✓ CompositionsBase 

   1467.9 ms  ✓ LevyArea
   6785.9 ms  ✓ ColorVectorSpace
   2550.8 ms  ✓ HypergeometricFunctions
   1522.2 ms  ✓ DiffRules
   1436.7 ms  ✓ SortingAlgorithms
   3629.5 ms  ✓ FastGaussQuadrature
   1760.4 ms  ✓ Xorg_libXext_jll
   2082.0 ms  ✓ Xorg_libXrender_jll
   7156.7 ms  ✓ ArnoldiMethod
   2383.4 ms  ✓ Xorg_libXfixes_jll
   1706.9 ms  ✓ Xorg_libxkbfile_jll
  41921.1 ms  ✓ SymbolServer
   1868.8 ms  ✓ Xorg_xcb_util_keysyms_jll
   1527.3 ms  ✓ Xorg_xcb_util_renderutil_jll
   1562.2 ms  ✓ Xorg_xcb_util_image_jll
   1540.0 ms  ✓ Xorg_xcb_util_wm_jll
    685.1 ms  ✓ ADTypes → ADTypesChainRulesCoreExt
   3017.1 ms  ✓ gdk_pixbuf_jll
    771.5 ms  ✓ AbstractFFTs → AbstractFFTsChainRulesCoreExt
    942.0 ms  ✓ EnzymeCore → EnzymeCoreChainRulesCoreExt
    753.6 ms  ✓ LinearMaps → LinearMapsChainRulesCoreExt
  14853.2 ms  ✓ StaticArrayInterface
   7365.4 ms  ✓ SymEngine
   6676.5 ms  ✓ QuadGK
    910.4 ms  ✓ DifferentiationInterface → DifferentiationInterfaceChainRulesCoreExt
    922.7 ms  ✓

   2735.3 ms  ✓ SparseMatrixColorings → SparseMatrixColoringsCliqueTreesExt
   1698.1 ms  ✓ Qt6ShaderTools_jll
   3154.6 ms  ✓ CliqueTrees → TreeWidthSolverExt
   1267.4 ms  ✓ Rsvg
   2477.4 ms  ✓ GR_jll
  13879.0 ms  ✓ RecursiveArrayTools
   4932.2 ms  ✓ FreeTypeAbstraction
  14438.2 ms  ✓ Distributions
    987.0 ms  ✓ RecursiveArrayTools → RecursiveArrayToolsStatisticsExt
   1234.1 ms  ✓ RecursiveArrayTools → RecursiveArrayToolsTablesExt
   1173.8 ms  ✓ RecursiveArrayTools → RecursiveArrayToolsFastBroadcastExt
   1354.8 ms  ✓ RecursiveArrayTools → RecursiveArrayToolsForwardDiffExt
   1251.0 ms  ✓ RecursiveArrayTools → RecursiveArrayToolsStructArraysExt
  13916.8 ms  ✓ DelaunayTriangulation
   1347.3 ms  ✓ RecursiveArrayTools → RecursiveArrayToolsSparseArraysExt
   9866.6 ms  ✓ Bonito
   3062.1 ms  ✓ Distributions → DistributionsTestExt
   7758.3 ms  ✓ OMEinsumContractionOrders
   5421.1 ms  ✓ Distributions → DistributionsChainRulesCoreExt
   8390.7 ms  ✓ Qt6Declarative_jll
  13746.4 

     Project No packages added to or removed from `~/.julia/environments/v1.12/Project.toml`
    Manifest No packages added to or removed from `~/.julia/environments/v1.12/Manifest.toml`
   Resolving package versions...
     Project No packages added to or removed from `~/.julia/environments/v1.12/Project.toml`
    Manifest No packages added to or removed from `~/.julia/environments/v1.12/Manifest.toml`
   Resolving package versions...
     Project No packages added to or removed from `~/.julia/environments/v1.12/Project.toml`
    Manifest No packages added to or removed from `~/.julia/environments/v1.12/Manifest.toml`


In [2]:
using Yao
using YaoPlots
using LinearAlgebra
using Kronecker

In [3]:
# Function to check Equalty up to phase
function is_global_phase_equal(ψ::Matrix{ComplexF64}, ϕ::Matrix{ComplexF64}; atol=1e-10)
    ψ = ψ / norm(ψ)
    ϕ = ϕ / norm(ϕ)
    inner = dot(conj(ϕ), ψ)
    return abs(abs(inner) - 1) < atol
end

is_global_phase_equal (generic function with 1 method)

In [4]:
xPhase = 1.503123
yPhase = 0.825345 
zPhase = 4.857364 

4.857364

In [5]:
# just to check endianness
state(ArrayReg(bit"01"))

4×1 Matrix{ComplexF64}:
 0.0 + 0.0im
 1.0 + 0.0im
 0.0 + 0.0im
 0.0 + 0.0im

In [6]:
# initialize register 
register = ArrayReg(bit"000")

ArrayReg{2, ComplexF64, Array...}
    active qubits: 3/3
    nlevel: 2

In [7]:
#prepare bell state
bellCirc = chain(3, put(2=>H))#chain(3, put(2=>H), control(2, 3=>X))
state1 = register |> bellCirc

ArrayReg{2, ComplexF64, Array...}
    active qubits: 3/3
    nlevel: 2

In [13]:
bellCirc2 = chain(3, control(2,3=>X))
state1 = state1 |> bellCirc2

ArrayReg{2, ComplexF64, Array...}
    active qubits: 3/3
    nlevel: 2

In [14]:
s1 = state(state1)

8×1 Matrix{ComplexF64}:
 0.7071067811865475 + 0.0im
                0.0 + 0.0im
 0.7071067811865475 + 0.0im
                0.0 + 0.0im
                0.0 + 0.0im
                0.0 + 0.0im
                0.0 + 0.0im
                0.0 + 0.0im

In [11]:
s1_alternate = reshape([0.707 + 0.000im, 0.000 + 0.000im, 0.000 + 0.000im, 0.707 + 0.000im, 0.000 + 0.000im, 0.000 + 0.000im, 0.000 + 0.000im, 0.000 + 0.000im], :, 1)

8×1 Matrix{ComplexF64}:
 0.707 + 0.0im
   0.0 + 0.0im
   0.0 + 0.0im
 0.707 + 0.0im
   0.0 + 0.0im
   0.0 + 0.0im
   0.0 + 0.0im
   0.0 + 0.0im

In [16]:
is_global_phase_equal(s1, s1_alternate)

false

In [12]:
x = s1/norm(s1)
y = s1_alternate/norm(s1_alternate)
inner = dot(conj(s1), s1_alternate)

0.499924494298889 + 0.0im

In [13]:
# Apply randomized rotations 
#rotCirc = chain(3, put(1=>Rx(xPhase)), put(1=>Ry(yPhase)), put(1=>Rz(zPhase)))
rotCirc = chain(3, put(1=>H))
state2 = state1 |> rotCirc

ArrayReg{2, ComplexF64, Array...}
    active qubits: 3/3
    nlevel: 2

In [14]:
state(state2)

8×1 Matrix{ComplexF64}:
 0.4999999999999999 + 0.0im
 0.4999999999999999 + 0.0im
                0.0 + 0.0im
                0.0 + 0.0im
                0.0 + 0.0im
                0.0 + 0.0im
 0.4999999999999999 + 0.0im
 0.4999999999999999 + 0.0im

In [15]:
entangleCirc = chain(3, control(1, 2=>X), put(1=>H))
state3 = state2 |> entangleCirc

ArrayReg{2, ComplexF64, Array...}
    active qubits: 3/3
    nlevel: 2

In [11]:
state(state3)

8×1 Matrix{ComplexF64}:
 -0.06988852469142956 + 0.0099499868085135im
 -0.25730436761243536 - 0.6548366622956676im
 -0.06988852469142956 + 0.0099499868085135im
 -0.25730436761243536 - 0.6548366622956676im
                  0.0 + 0.0im
                  0.0 + 0.0im
                  0.0 + 0.0im
                  0.0 + 0.0im

In [68]:
ket0 = [1, 0]
ket1 = [0, 1]

Id = [[1 0]; [0 1]]

P0 = ket0 * ket0'
P1 = ket1 * ket1'

expandedP0one = P0 ⊗ Id ⊗ Id
expandedP1one = P1 ⊗ Id ⊗ Id 

expandedP0two = Id ⊗ P0 ⊗ Id
expandedP1two = Id ⊗ P1 ⊗ Id 

8×8 Kronecker.KroneckerProduct{Int64, Kronecker.KroneckerProduct{Int64, Matrix{Int64}, Matrix{Int64}}, Matrix{Int64}}:
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  1  0  0  0  0  0
 0  0  0  1  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  1  0
 0  0  0  0  0  0  0  1

In [17]:
expandedP1two

8×8 Kronecker.KroneckerProduct{Int64, Kronecker.KroneckerProduct{Int64, Matrix{Int64}, Matrix{Int64}}, Matrix{Int64}}:
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  1  0  0  0  0  0
 0  0  0  1  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  1  0
 0  0  0  0  0  0  0  1

In [14]:
ψ = state(state3)
ψ_1 = expandedP0one * ψ
ψ_2 = expandedP1one * ψ

ψ_3 = expandedP0two * ψ
ψ_4 = expandedP1two * ψ

8×1 Matrix{ComplexF64}:
                  0.0 + 0.0im
                  0.0 + 0.0im
 -0.06988852469142956 + 0.0099499868085135im
 -0.25730436761243536 - 0.6548366622956676im
                  0.0 + 0.0im
                  0.0 + 0.0im
                  0.0 + 0.0im
                  0.0 + 0.0im

In [64]:
ket000 = ket0 ⊗ ket0 ⊗ ket0

8×1 Kronecker.KroneckerProduct{Int64, Kronecker.KroneckerProduct{Int64, Matrix{Int64}, Matrix{Int64}}, Matrix{Int64}}:
 1
 0
 0
 0
 0
 0
 0
 0

In [67]:
hadamard = (1/sqrt(2)) * [[1 1]; [1 -1]]

2×2 Matrix{Float64}:
 0.707107   0.707107
 0.707107  -0.707107